[default]
address = "127.0.0.1"
port = 8000
workers = 16
keep_alive = 5
ident = "Rocket"
log = "normal"
temp_dir = "/tmp"
cli_colors = true
## Please do not use this key, but generate your own with `openssl rand -base64 32`
secret_key = " nwGXgDz5m58F8OB2Df3LNEsEO+WVaSou0SqpOY9Ve5E="

[default.limits]
forms = "32KiB"
data-form = "2MiB"
file = "1KiB"
string = "8KiB"
json = "1MiB"
msgpack = "1MiB"

#[default.tls]
#certs = "/path/to/certs.pem"
#key = "/path/to/key.pem"

[default.shutdown]
ctrlc = true
signals = ["term"]
grace = 5
mercy = 5
force = true


[release]
port = 9999
